openapi: 3.1.0
info:
  title: Access Grants API
  version: 1.0.0
  description: API for managing resource access grants

paths:
  /admin/resource-access-grants:
    get:
      summary: Search resource access grants
      description: Search and filter resource access grants with pagination
      operationId: searchAccessGrants
      tags:
        - Access Grants
      security:
        - BearerAuth: []
      parameters:
        - name: resourceType
          in: query
          schema:
            type: string
          example: "CASE"
        - name: resourceId
          in: query
          schema:
            type: string
          example: "456"
        - name: subresourceType
          in: query
          schema:
            type: string
          example: "NOTE"
        - name: subresourceId
          in: query
          schema:
            type: string
        - name: authUserId
          in: query
          schema:
            type: string
            format: uuid
        - name: accessLevel
          in: query
          schema:
            type: string
            enum: [VIEW, EDIT, UPLOAD, ADMIN]
        - name: lawFirmId
          in: query
          schema:
            type: string
            format: uuid
        - name: page[number]
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page[size]
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 50
      responses:
        '200':
          description: List of matching grants
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResourceAccessGrant'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'

  /admin/resources/{resourceType}/{resourceId}/access-grants:
    get:
      summary: List grants for specific resource
      description: Get all access grants for a specific resource
      operationId: listResourceGrants
      tags:
        - Access Grants
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceType'
        - $ref: '#/components/parameters/ResourceId'
      responses:
        '200':
          description: List of grants for the resource
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResourceAccessGrant'

    post:
      summary: Create resource access grant
      description: Manually grant a user access to a resource
      operationId: createAccessGrant
      tags:
        - Access Grants
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceType'
        - $ref: '#/components/parameters/ResourceId'
        - name: Idempotency-Key
          in: header
          required: false
          schema:
            type: string
            maxLength: 64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccessGrantRequest'
      responses:
        '201':
          description: Grant created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceAccessGrant'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          description: User or resource type not found
        '409':
          description: Duplicate grant (grant already exists)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "DUPLICATE_GRANT"
                message: "Grant already exists for this user, resource, and access level"
                request_id: "req-12345"

  /admin/resources/{resourceType}/{resourceId}/access-grants/{authUserId}/{accessLevel}:
    delete:
      summary: Revoke resource access grant
      description: Remove a specific access grant
      operationId: revokeAccessGrant
      tags:
        - Access Grants
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceType'
        - $ref: '#/components/parameters/ResourceId'
        - name: authUserId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: accessLevel
          in: path
          required: true
          schema:
            type: string
            enum: [VIEW, EDIT, UPLOAD, ADMIN]
      responses:
        '204':
          description: Grant revoked successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          description: Grant not found

  /admin/resources/{resourceType}/{resourceId}/{subresourceType}/{subresourceId}/access-grants:
    get:
      summary: List grants for specific subresource
      description: Get all access grants for a specific subresource
      operationId: listSubresourceGrants
      tags:
        - Access Grants
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceType'
        - $ref: '#/components/parameters/ResourceId'
        - $ref: '#/components/parameters/SubresourceType'
        - $ref: '#/components/parameters/SubresourceId'
      responses:
        '200':
          description: List of grants for the subresource
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResourceAccessGrant'

    post:
      summary: Create subresource access grant
      description: Manually grant a user access to a subresource
      operationId: createSubresourceGrant
      tags:
        - Access Grants
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceType'
        - $ref: '#/components/parameters/ResourceId'
        - $ref: '#/components/parameters/SubresourceType'
        - $ref: '#/components/parameters/SubresourceId'
        - name: Idempotency-Key
          in: header
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccessGrantRequest'
      responses:
        '201':
          description: Subresource grant created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceAccessGrant'

  /admin/resources/{resourceType}/{resourceId}/{subresourceType}/{subresourceId}/access-grants/{authUserId}/{accessLevel}:
    delete:
      summary: Revoke subresource access grant
      description: Remove a specific subresource grant
      operationId: revokeSubresourceGrant
      tags:
        - Access Grants
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceType'
        - $ref: '#/components/parameters/ResourceId'
        - $ref: '#/components/parameters/SubresourceType'
        - $ref: '#/components/parameters/SubresourceId'
        - name: authUserId
          in: path
          required: true
          schema:
            type: string
        - name: accessLevel
          in: path
          required: true
          schema:
            type: string
            enum: [VIEW, EDIT, UPLOAD, ADMIN]
      responses:
        '204':
          description: Subresource grant revoked

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  parameters:
    ResourceType:
      name: resourceType
      in: path
      required: true
      schema:
        type: string
        pattern: '^[A-Z][A-Z0-9_]*$'
    ResourceId:
      name: resourceId
      in: path
      required: true
      schema:
        type: string
    SubresourceType:
      name: subresourceType
      in: path
      required: true
      schema:
        type: string
        pattern: '^[A-Z][A-Z0-9_]*$'
    SubresourceId:
      name: subresourceId
      in: path
      required: true
      schema:
        type: string

  schemas:
    ResourceAccessGrant:
      type: object
      properties:
        id:
          type: string
          format: uuid
        resource_type:
          type: string
        resource_id:
          type: string
        subresource_type:
          type: string
          nullable: true
        subresource_id:
          type: string
          nullable: true
        auth_user_id:
          type: string
          format: uuid
        access_level:
          type: string
          enum: [VIEW, EDIT, UPLOAD, ADMIN]
        grant_source:
          type: string
          enum: [MANUAL, ROLE, CASE_MEMBER, PARTNER_MEMBER, SYSTEM]
        starts_at:
          type: string
          format: date-time
        ends_at:
          type: string
          format: date-time
          nullable: true
        law_firm_id:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateAccessGrantRequest:
      type: object
      required:
        - auth_user_id
        - access_level
        - starts_at
      properties:
        auth_user_id:
          type: string
          format: uuid
        access_level:
          type: string
          enum: [VIEW, EDIT, UPLOAD, ADMIN]
        starts_at:
          type: string
          format: date-time
        ends_at:
          type: string
          format: date-time
          nullable: true
        subresource_type:
          type: string
        subresource_id:
          type: string

    PaginationMeta:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        request_id:
          type: string
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  responses:
    BadRequestError:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ForbiddenError:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
