openapi: 3.1.0
info:
  title: Resource Types API
  version: 1.0.0
  description: API for managing resource type and subtype registries

paths:
  /admin/resource-types:
    get:
      summary: List all resource types
      description: Retrieve all active resource types in the system
      operationId: listResourceTypes
      tags:
        - Resource Types
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of resource types
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResourceType'
              examples:
                success:
                  value:
                    data:
                      - id: "rt-001"
                        code: "CASE"
                        name: "Legal Case"
                        scope_type: "CASE"
                        id_format: "int64"
                        is_active: true
                        created_at: "2025-10-15T00:00:00Z"
                        updated_at: "2025-10-15T00:00:00Z"
                      - id: "rt-002"
                        code: "CLIENT"
                        name: "Client"
                        scope_type: "FIRM"
                        id_format: "uuid"
                        is_active: true
                        created_at: "2025-10-15T00:00:00Z"
                        updated_at: "2025-10-15T00:00:00Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /admin/resource-types/{resourceType}/subtypes:
    get:
      summary: List subtypes for a resource type
      description: Retrieve all active subtypes for a specific resource type
      operationId: listResourceSubtypes
      tags:
        - Resource Types
      security:
        - BearerAuth: []
      parameters:
        - name: resourceType
          in: path
          required: true
          description: Resource type code (e.g., CASE, INVOICE)
          schema:
            type: string
            pattern: '^[A-Z][A-Z0-9_]*$'
            example: "CASE"
      responses:
        '200':
          description: List of subtypes for the resource type
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResourceSubtype'
              examples:
                success:
                  value:
                    data:
                      - id: "rst-001"
                        resource_type_code: "CASE"
                        code: "NOTE"
                        name: "Case Note"
                        id_format: "int64"
                        is_active: true
                        created_at: "2025-10-15T00:00:00Z"
                        updated_at: "2025-10-15T00:00:00Z"
                      - id: "rst-002"
                        resource_type_code: "CASE"
                        code: "DOCUMENT"
                        name: "Case Document"
                        id_format: "uuid"
                        is_active: true
                        created_at: "2025-10-15T00:00:00Z"
                        updated_at: "2025-10-15T00:00:00Z"
                empty:
                  value:
                    data: []
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          description: Resource type not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "RESOURCE_TYPE_NOT_FOUND"
                message: "Resource type 'INVALID' does not exist"
                request_id: "req-12345"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ResourceType:
      type: object
      required:
        - id
        - code
        - name
        - scope_type
        - id_format
        - is_active
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier
        code:
          type: string
          pattern: '^[A-Z][A-Z0-9_]*$'
          description: Resource type code (uppercase)
          example: "CASE"
        name:
          type: string
          description: Human-readable name
          example: "Legal Case"
        scope_type:
          type: string
          enum: [GLOBAL, FIRM, ORG_UNIT, CASE]
          description: Boundary scope for this resource type
        id_format:
          type: string
          enum: [int64, uuid, string]
          description: Expected format for resource IDs
        is_active:
          type: boolean
          description: Whether the resource type is active
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    ResourceSubtype:
      type: object
      required:
        - id
        - resource_type_code
        - code
        - name
        - id_format
        - is_active
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier
        resource_type_code:
          type: string
          description: Parent resource type code
          example: "CASE"
        code:
          type: string
          pattern: '^[A-Z][A-Z0-9_]*$'
          description: Subtype code (uppercase)
          example: "NOTE"
        name:
          type: string
          description: Human-readable name
          example: "Case Note"
        id_format:
          type: string
          enum: [int64, uuid, string]
          description: Expected format for subresource IDs
        is_active:
          type: boolean
          description: Whether the subtype is active
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    ErrorResponse:
      type: object
      required:
        - code
        - message
        - request_id
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        request_id:
          type: string
          description: Request correlation ID
        details:
          type: array
          description: Field-level validation errors
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  responses:
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: "UNAUTHORIZED"
            message: "Authentication required"
            request_id: "req-12345"

    ForbiddenError:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: "FORBIDDEN"
            message: "Admin privileges required"
            request_id: "req-12345"
