import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Specifications sidebar (includes intro and overview)
  specsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'BDD Features',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'features/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'features'},
      ],
    },
    {
      type: 'category',
      label: 'Overview',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'specifications'},
      ],
    },
    {
      type: 'category',
      label: 'SpecKit Specifications',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'specs'},
      ],
    },
    {
      type: 'doc',
      id: 'speckit-guide',
      label: 'SpecKit Guide',
    },
  ],

  // Separate API Reference sidebar (only APIs, no specs or guides)
  apiSidebar: require('./docs/admin-api/sidebar.ts'),

  // User API Reference sidebar
  userApiSidebar: require('./docs/user-api/sidebar.ts'),

  // Separate C4 Models sidebar (architecture diagrams)
  c4Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'c4-models',
    },
  ],
};

export default sidebars;
