import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar (Specifications, Guides, Architecture)
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Specifications',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'specifications'},
      ],
    },
    {
      type: 'category',
      label: 'SpecKit Specifications',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'specs'},
      ],
    },
    {
      type: 'category',
      label: 'Architecture (C4 Models)',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'c4-models'},
      ],
    },
    {
      type: 'doc',
      id: 'speckit-guide',
      label: 'SpecKit Guide',
    },
  ],

  // Separate API Reference sidebar (only APIs, no specs or guides)
  apiSidebar: require('./docs/admin-api/sidebar.ts'),
};

export default sidebars;
