import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Backstage Specifications sidebar (unified documentation)
  specsSidebar: [
    'backstage/specifications/index',
    'backstage/specifications/backstage-api-specification',
    {
      type: 'category',
      label: 'Architecture (C4 Models)',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'backstage/c4-models/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'backstage/c4-models'},
      ],
    },
    {
      type: 'category',
      label: 'Admin Specifications',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'backstage/specifications/admin/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'backstage/specifications/admin'},
      ],
    },
  ],

  // Unified Backstage API sidebar (combines Admin API + User API)
  backstageApiSidebar: (() => {
    const adminSidebar = require('./docs/backstage/apis/admin/sidebar.ts');
    const userSidebar = require('./docs/backstage/apis/user/sidebar.ts');

    // Handle different module export formats (default export can be nested)
    let adminItems = adminSidebar;
    if (adminItems && typeof adminItems === 'object' && !Array.isArray(adminItems)) {
      // Try to unwrap: could be { default: [...] } or { default: { default: [...] } }
      adminItems = adminItems.default || adminItems.apisidebar || [];
      if (adminItems && typeof adminItems === 'object' && !Array.isArray(adminItems)) {
        adminItems = adminItems.default || adminItems.apisidebar || [];
      }
    }

    let userItems = userSidebar;
    if (userItems && typeof userItems === 'object' && !Array.isArray(userItems)) {
      userItems = userItems.default || userItems.apisidebar || [];
      if (userItems && typeof userItems === 'object' && !Array.isArray(userItems)) {
        userItems = userItems.default || userItems.apisidebar || [];
      }
    }

    // Ensure we have arrays
    const adminItemsArray = Array.isArray(adminItems) ? adminItems : [];
    const userItemsArray = Array.isArray(userItems) ? userItems : [];

    return [
      {
        type: 'category',
        label: 'Admin API',
        collapsed: false,
        link: {
          type: 'doc',
          id: 'backstage/apis/admin/law-firm-admin-provisioning-api-logto-managed-rbac',
        },
        items: adminItemsArray.slice(1), // Skip the intro doc
      },
      {
        type: 'category',
        label: 'User API',
        collapsed: false,
        link: {
          type: 'doc',
          id: 'backstage/apis/user/law-firm-user-portal-api',
        },
        items: userItemsArray.slice(1), // Skip the intro doc
      },
    ];
  })(),
};

export default sidebars;
